export const SET_STATUS = 'SET_STATUS'
export const SET_COLOR = 'SET_COLOR'
export const ADD_MOVE = 'ADD_MOVE'
export const RESET_MOVES = 'RESET_MOVES'
export const SET_MODE = 'SET_MODE'
export const SET_TURN = 'SET_TURN'